resource_group_name = "terraform-rg"
resource_group_location = "East US 2"
storage_account_name = "terraformstorage59"
storage_container_name = "data"
blob_storage_name = "sample.txt"
virtual_network_name = "terratrom-vn"